/**
 * ClickHouse erasure adapter — P0-D DPDP §12.
 * MV fan-out wiring — P1-F: loads targets from the generated erasure_targets.json manifest.
 *
 * @paradigm sql (deterministic; no LLM)
 *
 * Executes partition-scoped ALTER TABLE ... DELETE mutations on CH tables that
 * carry `customer_ref`. This is Tier 2 (CH silver) + Tier 3 (CH bronze) of the
 * five-tier erasure ladder.
 *
 * Design constraints (per architecture proposal §4.2):
 *  - ClickHouse ALTER TABLE ... DELETE does NOT cascade to MVs/projections.
 *    The caller (erase-subject use-case) must iterate the `erasure_targets`
 *    manifest and call this function for EVERY registered table + MV.
 *  - The `customer_ref` column MUST exist on the target table — if not, the
 *    delete is skipped and a warning is logged (defensive; prevents table-not-
 *    found from blocking the rest of the ladder).
 *  - `workspace_id` is ALWAYS a predicate — cross-workspace deletes are rejected.
 *
 * P1-F: MV fan-out completion.
 *   The hardcoded ERASURE_TARGETS list is replaced by `loadErasureTargetsFromManifest()`
 *   which reads tools/codegen/generated/erasure_targets.json at process startup.
 *   The manifest is generated by tools/codegen/gen_facts.py from
 *   docs/schema/canonical-facts.yaml and is enforced by the CI drift gate
 *   (tools/ci/check_codegen_drift.py). A new MV added without registering in the
 *   manifest → CI fails (tools/ci/check_erasure_mv_registration.py).
 *
 * Implementation note on CH mutations:
 *   `ALTER TABLE ... DELETE WHERE ...` is a mutation (not an MVCC operation).
 *   It is async by default; we issue it synchronously from the Brain process
 *   without waiting for the mutation to materialize (CH mutations run in the
 *   background). The subsequent COUNT(*) verification step may see in-flight
 *   mutations, so we issue `SYSTEM SYNC REPLICA` via a short wait. On a
 *   single-node local dev setup there is only one replica and the mutation
 *   completes quickly; in prod we rely on the mutation completing before the
 *   COUNT verification (configurable wait).
 *
 * The `chCommand` function (not exported from lib-clickhouse-ts — that library
 * only supports SELECT/INSERT) is implemented here as a narrow DDL-command
 * escape hatch that only the erasure orchestrator is authorised to call
 * (static gate: grep before deploy to ensure no other caller).
 */

import { createClient, type ClickHouseClient } from '@clickhouse/client'
import { readFileSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { TierVerificationResult } from '../../domain/consent/subject-erasure.js'

// ---------------------------------------------------------------------------
// Singleton erasure client (superuser privileges — mutations require it).
// Separate from the read client in lib-clickhouse-ts (which uses brain_app).
// In local dev, both map to the same CH instance.
// ---------------------------------------------------------------------------

let _erasureClient: ClickHouseClient | null = null

function getErasureClient(): ClickHouseClient {
  if (_erasureClient) return _erasureClient
  _erasureClient = createClient({
    url: process.env.CLICKHOUSE_URL ?? 'http://localhost:8123',
    username: process.env.CLICKHOUSE_ERASURE_USER ?? process.env.CLICKHOUSE_USER ?? 'brain_app',
    password: process.env.CLICKHOUSE_ERASURE_PASSWORD ?? process.env.CLICKHOUSE_PASSWORD ?? 'brain_app_pw',
    database: process.env.CLICKHOUSE_DATABASE ?? 'brain',
    application: 'brain-erasure-orchestrator',
    request_timeout: 60_000, // mutations can take longer than reads
  })
  return _erasureClient
}

/** Test-only: reset the singleton. */
export function _resetErasureClientForTest(): void {
  _erasureClient = null
}

// ---------------------------------------------------------------------------
// Erasure target types (the "erasure_targets manifest" from the plan).
// ---------------------------------------------------------------------------

export interface ErasureTarget {
  table: string           // fully qualified: "brain.<table>" or plain PG table name
  hasCustomerRef: boolean
  description: string
  /**
   * Whether to append FINAL on COUNT queries. ReplacingMergeTree tables need
   * FINAL to deduplicate; plain MergeTree tables (e.g. connector_raw_events)
   * do NOT support FINAL — omit it for append-only bronze.
   * MVs (has_customer_ref=false) are skipped for count-verify.
   */
  useFinal?: boolean
  /** Store type: 'clickhouse' or 'postgres'. Only CH targets get ALTER DELETE. */
  store?: string
  /** Target type from the manifest (bronze, silver_fact, silver_fact_pg_mirror, materialized_view). */
  type?: string
}

// ---------------------------------------------------------------------------
// Raw manifest shape from tools/codegen/generated/erasure_targets.json
// ---------------------------------------------------------------------------

interface ManifestTarget {
  table: string
  type: string
  store?: string
  has_customer_ref?: boolean
  customer_ref_column?: string
  note?: string
}

interface ErasureManifest {
  targets: ManifestTarget[]
}

// ---------------------------------------------------------------------------
// Manifest loading (P1-F): replaces hardcoded list with generated manifest.
//
// Resolves the manifest path relative to this file's location within the
// monorepo. At runtime (compiled), this file is at
//   apps/core-service/dist/infrastructure/erasure/clickhouse-eraser.js
// The manifest lives at:
//   tools/codegen/generated/erasure_targets.json
// which is 6 levels up from the compiled file location.
//
// We also support an override via ERASURE_MANIFEST_PATH env var for CI/test
// scenarios where the compiled path differs.
// ---------------------------------------------------------------------------

/**
 * Walk up from a starting directory until we find the monorepo root.
 * Identified by the presence of `tools/codegen/generated/erasure_targets.json`.
 * Returns null if not found within 10 levels.
 */
function _findRepoRoot(startDir: string): string | null {
  let current = startDir
  for (let i = 0; i < 10; i++) {
    const candidate = resolve(current, 'tools', 'codegen', 'generated', 'erasure_targets.json')
    if (existsSync(candidate)) return current
    const parent = dirname(current)
    if (parent === current) break // filesystem root
    current = parent
  }
  return null
}

/** Resolved path to the generated erasure_targets manifest. */
function _resolveManifestPath(): string {
  if (process.env['ERASURE_MANIFEST_PATH']) {
    return resolve(process.env['ERASURE_MANIFEST_PATH'])
  }

  // Determine the directory of this module file. Works in both ESM and CJS,
  // and in both source (tsx/vitest) and compiled (dist/) contexts.
  let dir: string
  try {
    dir = fileURLToPath(new URL('.', import.meta.url))
  } catch {
    // CJS fallback (ts-node in test environments where import.meta is unavailable)
    dir = typeof __dirname !== 'undefined' ? __dirname : process.cwd()
  }

  // Walk up the directory tree to find the monorepo root (contains tools/).
  // This is robust across:
  //   - source context: apps/core-service/src/infrastructure/erasure/ (4 levels to apps/core-service)
  //   - compiled context: apps/core-service/dist/infrastructure/erasure/ (same)
  const repoRoot = _findRepoRoot(dir)
  if (repoRoot) {
    return resolve(repoRoot, 'tools', 'codegen', 'generated', 'erasure_targets.json')
  }

  // Absolute fallback: try the known-good path relative to the repo root.
  // This is only reached if the walk-up fails (e.g. in a very unusual container layout).
  return resolve(dir, '..', '..', '..', '..', '..', '..', 'tools', 'codegen', 'generated', 'erasure_targets.json')
}

/**
 * Load the erasure_targets.json manifest and convert it to the ErasureTarget shape.
 *
 * Called once at module load time; result is cached in ERASURE_TARGETS_FROM_MANIFEST.
 * In test mode, the manifest override can be injected via ERASURE_MANIFEST_PATH.
 *
 * Rules applied when mapping manifest → ErasureTarget:
 *  - Only 'clickhouse' store targets get ALTER DELETE (PG mirrors are excluded
 *    from the CH erasure — they have their own PG wipe path).
 *  - MV targets (has_customer_ref=false) are included in the list so the
 *    fan-out covers them (the orchestrator skips the ALTER DELETE for targets
 *    with hasCustomerRef=false, but their presence in the list means a COUNT
 *    check runs if the MV writes data).
 *  - Bronze (connector_raw_events, MergeTree): useFinal=false.
 *  - Silver facts (ReplacingMergeTree): useFinal=true.
 */
export function loadErasureTargetsFromManifest(): ErasureTarget[] {
  const manifestPath = _resolveManifestPath()

  if (!existsSync(manifestPath)) {
    // Fallback to the hardcoded list if the manifest is not found.
    // This is a safety net for environments where the codegen has not been run.
    // CI will catch this via the drift gate (check_codegen_drift.py).
    process.stderr.write(
      `[clickhouse-eraser] WARNING: erasure_targets.json not found at ${manifestPath}. ` +
        'Falling back to hardcoded targets. Run tools/codegen/gen_facts.py to generate the manifest. ' +
        'CI will fail on drift if the manifest is missing.\n',
    )
    return _HARDCODED_FALLBACK_TARGETS
  }

  let manifest: ErasureManifest
  try {
    const raw = readFileSync(manifestPath, 'utf-8')
    manifest = JSON.parse(raw) as ErasureManifest
  } catch (err) {
    process.stderr.write(
      `[clickhouse-eraser] ERROR: failed to parse erasure_targets.json at ${manifestPath}: ${err}\n` +
        'Falling back to hardcoded targets.\n',
    )
    return _HARDCODED_FALLBACK_TARGETS
  }

  const targets: ErasureTarget[] = []

  for (const t of manifest.targets ?? []) {
    // Only CH targets receive ALTER DELETE in this adapter.
    // PG mirrors are handled by the PG tier (wipePgPii) — not included here.
    if (t.store === 'postgres') continue

    const isMv = t.type === 'materialized_view'
    const hasCustomerRef = isMv ? (t.has_customer_ref ?? false) : true

    // Bronze = plain MergeTree (no FINAL); silver = ReplacingMergeTree (FINAL needed).
    const useFinal = t.type === 'bronze' ? false : true

    targets.push({
      table: t.table,
      hasCustomerRef,
      description: t.note ?? `Erasure target: ${t.table} (${t.type ?? 'unknown'})`,
      useFinal,
      store: t.store,
      type: t.type,
    })
  }

  if (targets.length === 0) {
    process.stderr.write(
      '[clickhouse-eraser] WARNING: erasure_targets.json produced 0 CH targets. ' +
        'This may indicate a malformed manifest. Falling back to hardcoded targets.\n',
    )
    return _HARDCODED_FALLBACK_TARGETS
  }

  return targets
}

// ---------------------------------------------------------------------------
// Hardcoded fallback — used when the manifest is unavailable.
// This matches the P0-D state and is the safety net for environments where
// the codegen has not been run.
// ---------------------------------------------------------------------------

const _HARDCODED_FALLBACK_TARGETS: ErasureTarget[] = [
  {
    table: 'brain.connector_raw_events',
    hasCustomerRef: true,
    description: 'Bronze: verbatim vendor payload (PII-tokenized, customer_ref-keyed)',
    useFinal: false,
    store: 'clickhouse',
    type: 'bronze',
  },
  {
    table: 'brain.connector_order_facts',
    hasCustomerRef: true,
    description: 'Silver: order facts (customer_ref present per 05-schema-connector-facts.sql)',
    useFinal: true,
    store: 'clickhouse',
    type: 'silver_fact',
  },
]

// ---------------------------------------------------------------------------
// ERASURE_TARGETS — loaded from the manifest at module load time (P1-F).
//
// This replaces the P0-D hardcoded list. The manifest is generated by
// tools/codegen/gen_facts.py from docs/schema/canonical-facts.yaml.
// A new MV/table added without regenerating the manifest → CI fails.
// ---------------------------------------------------------------------------

export const ERASURE_TARGETS: ErasureTarget[] = loadErasureTargetsFromManifest()

// ---------------------------------------------------------------------------
// Core erasure operations
// ---------------------------------------------------------------------------

/**
 * Issue an ALTER TABLE ... DELETE mutation for a specific (workspace_id, customer_ref)
 * on a CH table. Returns immediately (CH runs the mutation asynchronously).
 *
 * STATIC GATE: only the erase-subject use-case may call this function.
 */
export async function issueChDelete(
  tableQualified: string,
  workspaceId: string,
  customerRef: string,
): Promise<void> {
  if (!workspaceId || !customerRef) {
    throw new Error(
      `[clickhouse-eraser] issueChDelete requires both workspaceId and customerRef. ` +
        `workspaceId="${workspaceId}" customerRef="${customerRef}"`,
    )
  }

  // Belt-and-suspenders: reject cross-workspace patterns.
  if (workspaceId.length < 10) {
    throw new Error(
      `[clickhouse-eraser] workspaceId appears malformed (too short): "${workspaceId}"`,
    )
  }

  const sql = `ALTER TABLE ${tableQualified} DELETE WHERE workspace_id = '${workspaceId.replace(/'/g, "''")}' AND customer_ref = '${customerRef.replace(/'/g, "''")}'`

  await getErasureClient().command({ query: sql })
}

/**
 * Wait for all pending mutations on a table to complete.
 * On a single-node setup this is fast; in production a bounded retry is needed.
 */
export async function waitForMutations(
  tableQualified: string,
  timeoutMs = 30_000,
): Promise<void> {
  const start = Date.now()
  while (Date.now() - start < timeoutMs) {
    const result = await getErasureClient().query({
      query: `
        SELECT count(*) AS pending
        FROM system.mutations
        WHERE database = 'brain'
          AND table = '${tableQualified.replace('brain.', '')}'
          AND is_done = 0
      `,
      format: 'JSONEachRow',
    })
    const rows = await result.json<{ pending: string }>()
    const pending = parseInt(rows[0]?.pending ?? '0', 10)
    if (pending === 0) return
    await new Promise((r) => setTimeout(r, 500))
  }
  // Timeout — log a warning but do not throw; the COUNT verification will catch any residual.
  process.stderr.write(
    `[clickhouse-eraser] waitForMutations timed out after ${timeoutMs}ms for table ${tableQualified}. ` +
      'COUNT=0 verification may see in-flight mutations.\n',
  )
}

/**
 * Count rows remaining for (workspace_id, customer_ref) on a CH table.
 * Used to produce the COUNT=0 verification artifact.
 *
 * @param useFinal - append FINAL for ReplacingMergeTree tables (dedup-correct count).
 *   Set to false for plain MergeTree tables (e.g. connector_raw_events) which do
 *   not support FINAL.
 */
export async function countChRows(
  tableQualified: string,
  workspaceId: string,
  customerRef: string,
  useFinal = true,
): Promise<number> {
  const finalClause = useFinal ? 'FINAL' : ''
  const result = await getErasureClient().query({
    query: `
      SELECT count(*) AS cnt
      FROM ${tableQualified} ${finalClause}
      WHERE workspace_id = '${workspaceId.replace(/'/g, "''")}' AND customer_ref = '${customerRef.replace(/'/g, "''")}'
    `,
    format: 'JSONEachRow',
  })
  const rows = await result.json<{ cnt: string }>()
  return parseInt(rows[0]?.cnt ?? '0', 10)
}

/**
 * Run the full CH erasure + count-verify loop over all registered targets.
 * Returns a TierVerificationResult per target (the DPB artifact fragment).
 */
export async function eraseAndVerifyChTiers(
  workspaceId: string,
  customerRef: string,
  targets: ErasureTarget[] = ERASURE_TARGETS,
): Promise<TierVerificationResult[]> {
  const results: TierVerificationResult[] = []

  for (const target of targets) {
    if (!target.hasCustomerRef) {
      // Skip tables without customer_ref — they are not in scope for key-based erasure.
      results.push({
        tier: 'ch',
        table: target.table,
        countRemaining: 0,
        verified: true,
      })
      continue
    }

    try {
      await issueChDelete(target.table, workspaceId, customerRef)
      // Wait for the mutation to materialize before counting.
      await waitForMutations(target.table)
      const count = await countChRows(target.table, workspaceId, customerRef, target.useFinal ?? true)
      results.push({
        tier: 'ch',
        table: target.table,
        countRemaining: count,
        verified: count === 0,
      })
    } catch (err) {
      results.push({
        tier: 'ch',
        table: target.table,
        countRemaining: -1, // sentinel: unknown — error during erasure
        verified: false,
      })
      process.stderr.write(
        `[clickhouse-eraser] error erasing table ${target.table}: ${err}\n`,
      )
    }
  }

  return results
}
