/**
 * Connector sync + fact-analytics barrel (Slice E).
 * Exposed to the gateway via @brain/core-connectors (the connectors index re-exports).
 */

export { syncConnector, type SyncResult, type SyncDeps } from './sync-use-cases.js'
export {
  type ConnectorFetch,
  type SyncWindow,
  type ShopifyPull,
  LiveConnectorFetch,
  defaultConnectorFetch,
  defaultWindow,
  shopifyBackfillDays,
  adsBackfillDays,
} from './provider-fetch.js'
export {
  decimalStringToMinorUnits,
  microsToMinorUnits,
  classifyPaymentMethod,
  resolveGstSlabBp,
  customerRef,
  INDIA_DEFAULT_GST_BP,
  type OrderFact,
  type LineItemFact,
  type ProductFact,
  type AdSpendFact,
} from './acl.js'
export {
  normalizeShopifyOrder,
  normalizeShopifyProduct,
  normalizeMetaSpend,
  normalizeGoogleSpend,
  type ShopifyOrderNode,
  type ShopifyProductNode,
  type MetaInsightRaw,
  type GoogleAdsRaw,
} from './normalizers.js'
export {
  readStoreSummary,
  readPnl,
  readMarketing,
  readIntegrations,
  readCogs,
  readCogsSettings,
  type CogsSettings,
  readProductPerformance,
  readWorkspaceMembers,
  readWorkspaceSettings,
  readShipmentAnalytics,
  readPincodes,
  readCodPrepaid,
  readCohorts,
  readLtv,
  readLifecycleStates,
  readOrderTimings,
  readFirstProductCascade,
  readDistributions,
  readCalendarReport,
  readPnlPeriodGrid,
  readDailyNetSales,
  readDailyAcquisition,
  readDistributionsGraphPoints,
  readShipmentRows,
  type FactShipmentRow,
  type FactShipmentPage,
  type ShipmentRowFiltersLocal,
  type PnlGranularity,
  type FactPnlPeriodRow,
  type FactStoreSummary,
  type FactPnl,
  type FactMarketing,
  type FactIntegrationRow,
  type FactCogs,
  type FactProductRow,
  type ReadProductPerformanceFilters,
  type FactMemberRow,
  type FactWorkspaceSettings,
  type FactShipmentAnalytics,
  type FactPincodeRow,
  type FactCodPrepaid,
  type FactCohortRow,
  type FactLtv,
  type FactLifecycle,
  type FactOrderTimings,
  type FactCascadeRow,
  type FactDistRow,
  type FactCalendarRow,
  type FactDailySalesRow,
  type FactDailyAcquisitionRow,
  type FactDistGraphPoint,
  // Team CRUD mutations (parity-38 feat-parity-w6b):
  listTeamPendingInvitations,
  inviteTeamMember,
  changeTeamMemberRole,
  removeTeamMember,
  revokeTeamInvite,
  transferTeamOwnership,
  type FactPendingInvitationRow,
  // Email/SMS performance read (parity-38):
  readEmailPerformance,
  type FactEmailPerfRow,
} from './fact-analytics.js'
