/**
 * Connector sync + fact-analytics barrel (Slice E).
 * Exposed to the gateway via @brain/core-connectors (the connectors index re-exports).
 */

export { syncConnector, type SyncResult, type SyncDeps } from './sync-use-cases.js'
export {
  type ConnectorFetch,
  type SyncWindow,
  type ShopifyPull,
  LiveConnectorFetch,
  defaultConnectorFetch,
  defaultWindow,
  shopifyBackfillDays,
  adsBackfillDays,
} from './provider-fetch.js'
export {
  decimalStringToMinorUnits,
  microsToMinorUnits,
  classifyPaymentMethod,
  resolveGstSlabBp,
  customerRef,
  INDIA_DEFAULT_GST_BP,
  type OrderFact,
  type LineItemFact,
  type ProductFact,
  type AdSpendFact,
} from './acl.js'
export {
  normalizeShopifyOrder,
  normalizeShopifyProduct,
  normalizeMetaSpend,
  normalizeGoogleSpend,
  type ShopifyOrderNode,
  type ShopifyProductNode,
  type MetaInsightRaw,
  type GoogleAdsRaw,
} from './normalizers.js'
export {
  readStoreSummary,
  readPnl,
  readMarketing,
  readIntegrations,
  readCogs,
  readProductPerformance,
  readWorkspaceMembers,
  readWorkspaceSettings,
  readShipmentAnalytics,
  readPincodes,
  readCodPrepaid,
  readCohorts,
  readLtv,
  readLifecycleStates,
  readOrderTimings,
  readFirstProductCascade,
  readDistributions,
  readCalendarReport,
  type FactStoreSummary,
  type FactPnl,
  type FactMarketing,
  type FactIntegrationRow,
  type FactCogs,
  type FactProductRow,
  type FactMemberRow,
  type FactWorkspaceSettings,
  type FactShipmentAnalytics,
  type FactPincodeRow,
  type FactCodPrepaid,
  type FactCohortRow,
  type FactLtv,
  type FactLifecycle,
  type FactOrderTimings,
  type FactCascadeRow,
  type FactDistRow,
  type FactCalendarRow,
} from './fact-analytics.js'
