-- _divop_template.sql
-- CF-C4-RATIO-DIVOP-1 (CRITICAL): intDiv + null-guard template for EVERY ratio MV expression.
--
-- @paradigm: sql
--
-- BANNED — ClickHouse `/` on Int64 returns Float64 (NOT integer FLOOR):
--   total_ad_spend_mu * 10000 / net_sales_mu          -- returns Float64: coercion garbage / inf / Int-max on zero-denom
--
-- REQUIRED — integer FLOOR + fail-closed NULL on zero/absent denominator:
--   if(<denom> > 0, intDiv(<num>, <denom>), NULL)
--
-- This file is the authoritative expression template.
-- NO MV body may contain a `/` operator on metric columns.
-- The static grep gate (CF-C4-SINGLE-WRITER-GREP-2 / V4) enforces this.
--
-- ─────────────────────────────────────────────────────────────────────────────
-- TEMPLATE (copy-paste into every MV SELECT that produces a ratio):
-- ─────────────────────────────────────────────────────────────────────────────

-- Pattern A: basis-points ratio (×10000) — e.g. rto_rate_bp, acos_bp, conversion_rate_bp,
--            prepaid_rate_bp, meta_ctr_bp, google_ctr_bp, blended_roas_x100
--
--   if(<denom_col> > 0, intDiv(<num_col> * 10000, <denom_col>), NULL) AS <metric_name>_bp

-- Pattern B: money-unit ratio (NOT ×10000) — e.g. aov_mu, meta_cpc_mu, meta_cpm_mu,
--            google_avg_cpc_mu
--
--   if(<denom_col> > 0, intDiv(<num_col>, <denom_col>), NULL) AS <metric_name>_mu

-- Pattern C: prorated daily allocation — misc_expenses_prorated_mu
--   CF-C4-PRORATED-DIVOP-1: NEVER divide by 30 constant; use toDaysInMonth(date).
--
--   if(toDaysInMonth(date) > 0, intDiv(monthly_amount_mu, toDaysInMonth(date)), NULL) AS misc_expenses_prorated_mu
--
--   NOTE: toDaysInMonth(date) is always ≥28, so the guard is technically redundant,
--   but is kept for defence-in-depth and to satisfy the uniform null-guard contract.

-- ─────────────────────────────────────────────────────────────────────────────
-- WORKED EXAMPLES (all tested by V3 isolation suite + M4 round-trip fixtures)
-- ─────────────────────────────────────────────────────────────────────────────

-- rto_rate_bp:  rto_orders=150, total_shipments=1000 → intDiv(150*10000, 1000) = 1500 bp = 15.00%
-- rto_rate_bp:  rto_orders=1,   total_shipments=0    → NULL  (zero-denom guard, never inf/Int-max)
-- aov_mu:       net_sales_mu=1000000, order_count=47 → intDiv(1000000, 47) = 21276 mu (FLOOR, not 21276.59...)
-- conversion_bp: orders=1, sessions=3               → intDiv(1*10000, 3) = 3333 bp (FLOOR, not 3333.33...)
-- misc_prorated: monthly_amount_mu=310000, date='2026-02-15' (28 days)
--              → intDiv(310000, 28) = 11071 mu  (NOT 310000/30 = 10333 — correct calendar-aware proration)
-- misc_prorated: monthly_amount_mu=310000, date='2026-03-15' (31 days)
--              → intDiv(310000, 31) = 10000 mu

-- ─────────────────────────────────────────────────────────────────────────────
-- WHY NOT `/`: ClickHouse arithmetic semantics reference
-- ─────────────────────────────────────────────────────────────────────────────
-- ClickHouse `/` operator applied to integer types returns Float64 (not Int64 truncated).
-- For a zero denominator, Float64 division produces `inf` or `-inf`, which ClickHouse
-- implicitly coerces to INT64_MAX (9223372036854775807) or INT64_MIN on insertion into
-- an integer column — a sentinel value indistinguishable from a legitimate metric.
-- All positive-integer test fixtures produce the same value via `/` as via `intDiv` (because
-- float truncation == floor for positive values), making the bug invisible until a
-- zero-denominator day or a value where float representation diverges from integer floor
-- (e.g. large numerator × 10000 may lose mantissa bits in Float64).
-- intDiv(a, b) is defined as: truncate(a / b) for b ≠ 0; behaviour on b=0 is platform-
-- specific and must be guarded — hence the explicit `if(denom > 0, intDiv(...), NULL)`.
