# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain.metrics.v1 import metrics_pb2 as brain_dot_metrics_dot_v1_dot_metrics__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain/metrics/v1/metrics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MetricsServiceStub(object):
    """---------------------------------------------------------------------------
    MetricsService — the gRPC contract for the api-gateway DataPlanePort
    (analytics read path). Bound in-process / localhost-loopback in Phase 0–1.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryMetrics = channel.unary_unary(
                '/brain.metrics.v1.MetricsService/QueryMetrics',
                request_serializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.QueryMetricsRequest.SerializeToString,
                response_deserializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.QueryMetricsResponse.FromString,
                _registered_method=True)
        self.GetKpiSummary = channel.unary_unary(
                '/brain.metrics.v1.MetricsService/GetKpiSummary',
                request_serializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetKpiSummaryRequest.SerializeToString,
                response_deserializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetKpiSummaryResponse.FromString,
                _registered_method=True)
        self.GetPnlWaterfall = channel.unary_unary(
                '/brain.metrics.v1.MetricsService/GetPnlWaterfall',
                request_serializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetPnlWaterfallRequest.SerializeToString,
                response_deserializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetPnlWaterfallResponse.FromString,
                _registered_method=True)


class MetricsServiceServicer(object):
    """---------------------------------------------------------------------------
    MetricsService — the gRPC contract for the api-gateway DataPlanePort
    (analytics read path). Bound in-process / localhost-loopback in Phase 0–1.
    ---------------------------------------------------------------------------
    """

    def QueryMetrics(self, request, context):
        """Query raw metric rows from the computed MV (wraps query_metrics).
        Workspace-scoped, fail-closed (UnscopedQueryError if workspace_id empty).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKpiSummary(self, request, context):
        """Get typed KPI summary strip for a date range.
        Every field is a named registry metric — no derived/ad-hoc values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPnlWaterfall(self, request, context):
        """Get P&L / CM waterfall steps for a date range (Visx chart data).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MetricsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMetrics,
                    request_deserializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.QueryMetricsRequest.FromString,
                    response_serializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.QueryMetricsResponse.SerializeToString,
            ),
            'GetKpiSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKpiSummary,
                    request_deserializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetKpiSummaryRequest.FromString,
                    response_serializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetKpiSummaryResponse.SerializeToString,
            ),
            'GetPnlWaterfall': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPnlWaterfall,
                    request_deserializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetPnlWaterfallRequest.FromString,
                    response_serializer=brain_dot_metrics_dot_v1_dot_metrics__pb2.GetPnlWaterfallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain.metrics.v1.MetricsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain.metrics.v1.MetricsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MetricsService(object):
    """---------------------------------------------------------------------------
    MetricsService — the gRPC contract for the api-gateway DataPlanePort
    (analytics read path). Bound in-process / localhost-loopback in Phase 0–1.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def QueryMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.metrics.v1.MetricsService/QueryMetrics',
            brain_dot_metrics_dot_v1_dot_metrics__pb2.QueryMetricsRequest.SerializeToString,
            brain_dot_metrics_dot_v1_dot_metrics__pb2.QueryMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKpiSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.metrics.v1.MetricsService/GetKpiSummary',
            brain_dot_metrics_dot_v1_dot_metrics__pb2.GetKpiSummaryRequest.SerializeToString,
            brain_dot_metrics_dot_v1_dot_metrics__pb2.GetKpiSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPnlWaterfall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.metrics.v1.MetricsService/GetPnlWaterfall',
            brain_dot_metrics_dot_v1_dot_metrics__pb2.GetPnlWaterfallRequest.SerializeToString,
            brain_dot_metrics_dot_v1_dot_metrics__pb2.GetPnlWaterfallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
