// @paradigm: sql
//
// Correlation ID 4-tuple — extracted from incoming HTTP headers, propagated
// into every log line, then forwarded on outgoing calls so a single
// `request_id` traces a browser action through web → api-gateway → core →
// database and back. This is the spine of every Brain trace.
//
// Headers used (canonical, lowercase — Node sets them lowercase regardless of
// what the client sends):
//   x-request-id     : per-request UUID. Generated by the FIRST hop (browser or
//                      Next middleware) and propagated unchanged downstream.
//   x-trace-id       : per-trace UUID. May span multiple requests in a flow
//                      (e.g. a tRPC batch). Propagates with the request.
//   x-brain-workspace: the workspace the request operates against. Set by the
//                      authed client; the gateway VALIDATES it against the
//                      verified JWT membership before any data-plane call.
//   x-brain-user     : the verified user's `sub` (NOT the email). Added by the
//                      api-gateway after JWT verify; never trusted as an input.
//
// Anything missing → generated server-side at the FIRST hop that needs it.
//
// NEVER pass PII (email, full name, phone) via correlation headers.

// Use the web-standard crypto.randomUUID() (available on globalThis in Node
// 19+ AND every modern browser) so this module bundles cleanly for the
// browser — webpack can't resolve `node:crypto` for client code.

export interface CorrelationContext {
  request_id: string;
  trace_id: string;
  workspace_id?: string;
  user_id?: string;
}

export type CorrelationHeaders = Record<string, string | undefined>;

export const REQUEST_ID_HEADER = 'x-request-id' as const;
export const TRACE_ID_HEADER = 'x-trace-id' as const;
export const WORKSPACE_HEADER = 'x-brain-workspace' as const;
export const USER_HEADER = 'x-brain-user' as const;

/**
 * Generate a fresh correlation ID. Uses the web-standard crypto.randomUUID
 * (available on Node 19+ and every modern browser) so this works in both
 * server and browser bundles.
 */
export function newCorrelationId(): string {
  const c = globalThis.crypto;
  if (c?.randomUUID) return c.randomUUID();
  // Extremely defensive fallback — only fires on a non-secure-context older
  // browser (we don't target those; this exists so a missing crypto never
  // throws and leaves traces empty).
  const r = (Math.random() * 1e16).toString(16);
  return `00000000-0000-4000-8000-${r.padStart(12, '0').slice(0, 12)}`;
}

/**
 * Read the correlation 4-tuple from incoming headers, generating fresh UUIDs
 * for `request_id` / `trace_id` when absent. `workspace_id` and `user_id` stay
 * undefined here — they're filled in by the auth middleware after JWT verify.
 *
 * Accepts the raw `headers` map from Fastify, Next.js, or Node http; values
 * may be string, string[], or undefined (we keep the first if array).
 */
export function extractCorrelation(
  headers: Readonly<Record<string, string | string[] | undefined>>,
): CorrelationContext {
  const pickFirst = (v: string | string[] | undefined): string | undefined => {
    if (Array.isArray(v)) return v[0];
    return v?.trim() || undefined;
  };

  return {
    request_id: pickFirst(headers[REQUEST_ID_HEADER]) ?? newCorrelationId(),
    trace_id: pickFirst(headers[TRACE_ID_HEADER]) ?? newCorrelationId(),
    workspace_id: pickFirst(headers[WORKSPACE_HEADER]),
    user_id: pickFirst(headers[USER_HEADER]),
  };
}

/**
 * Build the outgoing header set for forwarding the correlation context to the
 * NEXT hop (e.g. web → api-gateway, api-gateway → core gRPC). Only includes
 * fields that are set — never serializes `undefined` strings.
 */
export function buildCorrelationHeaders(
  ctx: CorrelationContext,
): CorrelationHeaders {
  const h: CorrelationHeaders = {
    [REQUEST_ID_HEADER]: ctx.request_id,
    [TRACE_ID_HEADER]: ctx.trace_id,
  };
  if (ctx.workspace_id) h[WORKSPACE_HEADER] = ctx.workspace_id;
  if (ctx.user_id) h[USER_HEADER] = ctx.user_id;
  return h;
}
