# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brain/ingestion/v1/ingestion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'brain/ingestion/v1/ingestion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"brain/ingestion/v1/ingestion.proto\x12\x12\x62rain.ingestion.v1\"\xd8\x01\n\x15ReceiveWebhookRequest\x12\x0e\n\x06vendor\x18\x01 \x01(\t\x12\x10\n\x08raw_body\x18\x02 \x01(\x0c\x12G\n\x07headers\x18\x03 \x03(\x0b\x32\x36.brain.ingestion.v1.ReceiveWebhookRequest.HeadersEntry\x12\x12\n\nrequest_id\x18\x04 \x01(\t\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xea\x01\n\x16ReceiveWebhookResponse\x12\x43\n\x07outcome\x18\x01 \x01(\x0e\x32\x32.brain.ingestion.v1.ReceiveWebhookResponse.Outcome\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"w\n\x07Outcome\x12\x17\n\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n\x10OUTCOME_ACCEPTED\x10\x01\x12\x14\n\x10OUTCOME_REJECTED\x10\x02\x12\x12\n\x0eOUTCOME_PARKED\x10\x03\x12\x13\n\x0fOUTCOME_IGNORED\x10\x04\x32\x7f\n\x14WebhookIngestService\x12g\n\x0eReceiveWebhook\x12).brain.ingestion.v1.ReceiveWebhookRequest\x1a*.brain.ingestion.v1.ReceiveWebhookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain.ingestion.v1.ingestion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVEWEBHOOKREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_RECEIVEWEBHOOKREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_RECEIVEWEBHOOKREQUEST']._serialized_start=59
  _globals['_RECEIVEWEBHOOKREQUEST']._serialized_end=275
  _globals['_RECEIVEWEBHOOKREQUEST_HEADERSENTRY']._serialized_start=229
  _globals['_RECEIVEWEBHOOKREQUEST_HEADERSENTRY']._serialized_end=275
  _globals['_RECEIVEWEBHOOKRESPONSE']._serialized_start=278
  _globals['_RECEIVEWEBHOOKRESPONSE']._serialized_end=512
  _globals['_RECEIVEWEBHOOKRESPONSE_OUTCOME']._serialized_start=393
  _globals['_RECEIVEWEBHOOKRESPONSE_OUTCOME']._serialized_end=512
  _globals['_WEBHOOKINGESTSERVICE']._serialized_start=514
  _globals['_WEBHOOKINGESTSERVICE']._serialized_end=641
# @@protoc_insertion_point(module_scope)
