# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain.ingestion.v1 import ingestion_pb2 as brain_dot_ingestion_dot_v1_dot_ingestion__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain/ingestion/v1/ingestion_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebhookIngestServiceStub(object):
    """WebhookIngestService is the internal gRPC service that receives webhook
    events forwarded byte-faithfully from the api-gateway.

    INTERNAL-ONLY — not exposed via public ingress (PLACEMENT-1 / TRANSPORT-1).
    The api-gateway holds the public surface (rate-limit, body-cap, 200/401 mapping).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveWebhook = channel.unary_unary(
                '/brain.ingestion.v1.WebhookIngestService/ReceiveWebhook',
                request_serializer=brain_dot_ingestion_dot_v1_dot_ingestion__pb2.ReceiveWebhookRequest.SerializeToString,
                response_deserializer=brain_dot_ingestion_dot_v1_dot_ingestion__pb2.ReceiveWebhookResponse.FromString,
                _registered_method=True)


class WebhookIngestServiceServicer(object):
    """WebhookIngestService is the internal gRPC service that receives webhook
    events forwarded byte-faithfully from the api-gateway.

    INTERNAL-ONLY — not exposed via public ingress (PLACEMENT-1 / TRANSPORT-1).
    The api-gateway holds the public surface (rate-limit, body-cap, 200/401 mapping).
    """

    def ReceiveWebhook(self, request, context):
        """ReceiveWebhook accepts a raw webhook body + full forwarded headers from the
        api-gateway and runs the verify-first / default-deny state machine:
        1. unknown/empty vendor                    → REJECTED (default-deny)
        2. missing/empty signature header          → REJECTED
        3. secret retrieval fails                  → REJECTED (default-deny)
        4. HMAC verify returns false               → REJECTED
        5. external_identity unmapped              → PARKED  (no DB write)
        6. topic not in allowlist                  → IGNORED (no DB write)
        7. verify + map + topic OK                 → ACCEPTED (upsert + Kafka produce)

        The vendor field is the registry dispatch key — Shopify is "shopify",
        not the shape.  Adding vendor #2 adds a WEBHOOK_VERIFIERS entry only
        (no proto change, no servicer change, no route change).

        Response carries ONLY outcome + request_id (NEVERLOG-1).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebhookIngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveWebhook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveWebhook,
                    request_deserializer=brain_dot_ingestion_dot_v1_dot_ingestion__pb2.ReceiveWebhookRequest.FromString,
                    response_serializer=brain_dot_ingestion_dot_v1_dot_ingestion__pb2.ReceiveWebhookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain.ingestion.v1.WebhookIngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain.ingestion.v1.WebhookIngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebhookIngestService(object):
    """WebhookIngestService is the internal gRPC service that receives webhook
    events forwarded byte-faithfully from the api-gateway.

    INTERNAL-ONLY — not exposed via public ingress (PLACEMENT-1 / TRANSPORT-1).
    The api-gateway holds the public surface (rate-limit, body-cap, 200/401 mapping).
    """

    @staticmethod
    def ReceiveWebhook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.ingestion.v1.WebhookIngestService/ReceiveWebhook',
            brain_dot_ingestion_dot_v1_dot_ingestion__pb2.ReceiveWebhookRequest.SerializeToString,
            brain_dot_ingestion_dot_v1_dot_ingestion__pb2.ReceiveWebhookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
