# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from brain.intelligence.v1 import intelligence_pb2 as brain_dot_intelligence_dot_v1_dot_intelligence__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in brain/intelligence/v1/intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelligenceServiceStub(object):
    """---------------------------------------------------------------------------
    IntelligenceService — the gRPC contract for the api-gateway DataPlanePort
    (intelligence read + write path). Bound in-process / loopback in Phase 0–1.
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMorningBrief = channel.unary_unary(
                '/brain.intelligence.v1.IntelligenceService/GetMorningBrief',
                request_serializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.GetMorningBriefRequest.SerializeToString,
                response_deserializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.GetMorningBriefResponse.FromString,
                _registered_method=True)
        self.SubmitInsightResponse = channel.unary_unary(
                '/brain.intelligence.v1.IntelligenceService/SubmitInsightResponse',
                request_serializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.SubmitInsightResponseRequest.SerializeToString,
                response_deserializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.SubmitInsightResponseResponse.FromString,
                _registered_method=True)
        self.RegisterPushToken = channel.unary_unary(
                '/brain.intelligence.v1.IntelligenceService/RegisterPushToken',
                request_serializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.RegisterPushTokenRequest.SerializeToString,
                response_deserializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.RegisterPushTokenResponse.FromString,
                _registered_method=True)


class IntelligenceServiceServicer(object):
    """---------------------------------------------------------------------------
    IntelligenceService — the gRPC contract for the api-gateway DataPlanePort
    (intelligence read + write path). Bound in-process / loopback in Phase 0–1.
    ---------------------------------------------------------------------------
    """

    def GetMorningBrief(self, request, context):
        """Get the Morning Brief for a workspace and date.
        Returns ≤3 InsightItems with the amended contract.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInsightResponse(self, request, context):
        """Submit approve/reject/edit response to a Morning Brief insight.
        Idempotent: same idempotency_key → returns cached response, ONE decision-log row.
        CF-C6-MB-IDEMPOTENCY-1.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPushToken(self, request, context):
        """Register / rotate an Expo push token for a user device.
        Idempotent upsert on (workspace_id, user_id, device_id).
        CF-C6-MB-PUSH-TOKEN-1: token registration only; SEND is notifications-service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMorningBrief': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMorningBrief,
                    request_deserializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.GetMorningBriefRequest.FromString,
                    response_serializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.GetMorningBriefResponse.SerializeToString,
            ),
            'SubmitInsightResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInsightResponse,
                    request_deserializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.SubmitInsightResponseRequest.FromString,
                    response_serializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.SubmitInsightResponseResponse.SerializeToString,
            ),
            'RegisterPushToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPushToken,
                    request_deserializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.RegisterPushTokenRequest.FromString,
                    response_serializer=brain_dot_intelligence_dot_v1_dot_intelligence__pb2.RegisterPushTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain.intelligence.v1.IntelligenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain.intelligence.v1.IntelligenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelligenceService(object):
    """---------------------------------------------------------------------------
    IntelligenceService — the gRPC contract for the api-gateway DataPlanePort
    (intelligence read + write path). Bound in-process / loopback in Phase 0–1.
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def GetMorningBrief(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.intelligence.v1.IntelligenceService/GetMorningBrief',
            brain_dot_intelligence_dot_v1_dot_intelligence__pb2.GetMorningBriefRequest.SerializeToString,
            brain_dot_intelligence_dot_v1_dot_intelligence__pb2.GetMorningBriefResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInsightResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.intelligence.v1.IntelligenceService/SubmitInsightResponse',
            brain_dot_intelligence_dot_v1_dot_intelligence__pb2.SubmitInsightResponseRequest.SerializeToString,
            brain_dot_intelligence_dot_v1_dot_intelligence__pb2.SubmitInsightResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPushToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.intelligence.v1.IntelligenceService/RegisterPushToken',
            brain_dot_intelligence_dot_v1_dot_intelligence__pb2.RegisterPushTokenRequest.SerializeToString,
            brain_dot_intelligence_dot_v1_dot_intelligence__pb2.RegisterPushTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
